[package]
name = "craftmine_asset_java"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.15"
serde_json = "1.0"

bevy = { workspace = true }
